import Image from "next/image";
import {ArrowUpRight,ArrowDown,BookOpen,GraduationCap,MapPin,Mail,Users,MessageCircle,HeartHandshake,Building2,Scale,Search,Check,PenLine,Quote} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Navbar,Motion,CVButton,AcademicGallery,ContactForm,Copyright} from "@/components/portfolio-interactions";
import {profile,navigation,socials} from "@/data/profile";
import {semesters,interests,highlights} from "@/data/education";
import {research} from "@/data/research";
import {projects} from "@/data/projects";
import {skills,digitalSkills} from "@/data/skills";
import {experience} from "@/data/experience";
import {certificates} from "@/data/certificates";
function Heading({label,title,description}:{label:string;title:string;description?:string}){return <div className="section-heading"><p className="eyebrow">{label}</p><h2>{title}</h2>{description&&<p>{description}</p>}</div>}
const icons=[Scale,BookOpen,Users,HeartHandshake,Building2,Search];
export default function Home(){const publishedExperience=experience.filter(x=>x.published);const publishedCertificates=certificates.filter(x=>x.published);return <><a href="#main" className="skip-link">Skip to content</a><Navbar/><main id="main">
<section id="home" className="hero section-wrap"><div className="hero-copy"><p className="hero-badge"><GraduationCap size={16}/>{profile.semester} · Sociology · University of Dhaka</p><p className="hello">Hello, I’m</p><h1>Kaniz Sadia<br/><em>Kabita<span>.</span></em></h1><p className="hero-title">Understanding society.<br/>Exploring change. Creating impact.</p><p className="hero-intro">{profile.intro}</p><div className="hero-actions"><Button asChild className="cta"><a href="#projects">View my work <ArrowUpRight size={18}/></a></Button><CVButton/></div><div className="hero-meta"><MapPin size={15}/><span>{profile.location}</span><span className="meta-line"/><a href="#contact">Contact me <ArrowUpRight size={14}/></a></div></div><div className="hero-visual"><span className="portrait-outline" aria-hidden="true"/><div className="hero-photo"><Image src={profile.portrait} alt="Kaniz Sadia Kabita holding flowers on university steps" fill priority sizes="(max-width: 768px) 85vw, 43vw" unoptimized/></div><div className="academic-float"><span className="float-icon"><GraduationCap size={25}/></span><span><strong>{profile.university}</strong><small>BSS in Sociology</small></span></div><div className="portrait-note"><span className="note-line"/>Curiosity is where it begins.</div><span className="hero-side-note">PEOPLE · PERSPECTIVES · POSSIBILITIES</span></div></section>
<div className="intro-strip"><div className="section-wrap"><span>Sociology</span><span>Research</span><span>Education</span><span>Community</span><span>Social change</span><a href="#study" aria-label="Explore my academic journey"><ArrowDown size={19}/></a></div></div>
<section id="study" className="section-wrap section-pad reveal"><Heading label="01 / MY ACADEMIC JOURNEY" title="Learning to see the bigger picture." description="Building knowledge through Sociology, research, and academic curiosity."/><div className="education-layout"><div className="education-card"><GraduationCap size={34} strokeWidth={1.3}/><span className="small-caps">UNDERGRADUATE STUDENT</span><h3>{profile.university}</h3><p>{profile.degree}</p><div className="edu-footer"><span>{profile.department}</span><span><MapPin size={14}/>{profile.location}</span></div></div><div className="academic-record"><p className="eyebrow">A JOURNEY IN PROGRESS</p><h3>A strong foundation.<br/>An open mind.</h3><p>Maintaining a strong academic record throughout my undergraduate studies, with consistently excellent performance across previous and current semesters.</p><div className="semester-list">{semesters.map(s=><div key={s.number} className={s.number===5?"semester current":"semester"}><span className="semester-point">{s.number===5?<BookOpen size={15}/>:<Check size={14}/>}</span><strong>0{s.number}</strong><span>{s.status}</span>{s.cgpa&&<small>CGPA {s.cgpa}</small>}</div>)}</div></div></div><div className="interest-row"><p>Areas of academic interest</p><div className="tags">{interests.map(i=><span key={i}>{i}</span>)}</div></div></section>
<section id="story" className="story-section"><div className="section-wrap section-pad"><div className="story-layout reveal"><div className="story-image"><Image src="/images/tree.webp" alt="Kaniz standing beside a tree on campus" fill sizes="(max-width:768px) 90vw, 36vw" unoptimized/><span>A little about who I am</span></div><div className="story-copy"><Heading label="02 / MY STORY" title="Behind every question, a human story."/>{profile.story.map(t=><p key={t}>{t}</p>)}<p className="signature">Kaniz Sadia Kabita</p><span className="story-home">From Mohadevpur, Naogaon. Growing in Dhaka.</span></div></div><div className="story-highlights reveal">{[{icon:Search,title:"A curious mind",text:"Exploring social issues through observation, interviews, surveys, and academic inquiry."},{icon:MessageCircle,title:"A listening ear",text:"Understanding communities and taking part in initiatives that create social value."},{icon:HeartHandshake,title:"A sense of purpose",text:"Connecting research with inclusive development and evidence-based social policy."}].map(({icon:Icon,title,text})=><article key={title}><Icon size={25} strokeWidth={1.4}/><h3>{title}</h3><p>{text}</p></article>)}</div><div className="gallery-heading reveal"><Heading label="LIFE BEYOND THE LECTURE HALL" title="Moments along the way."/><p>A few glimpses of my university life.<br/>Small moments, lasting memories.</p></div><AcademicGallery/></div></section>
<section className="section-wrap section-pad reveal"><div className="heading-split"><Heading label="03 / WHAT I EXPLORE" title="Questions that keep me curious."/><p>My research interests sit at the intersection of people, opportunity, and social change.</p></div><div className="research-grid">{research.map((r,i)=>{const Icon=icons[i];return <article className="research-card" key={r.title}><div><Icon size={27} strokeWidth={1.25}/><span>0{i+1}</span></div><h3>{r.title}</h3><p>{r.description}</p></article>})}</div></section>
<section id="projects" className="projects-section section-pad"><div className="section-wrap"><div className="heading-split reveal"><Heading label="04 / PROJECTS & RESEARCH" title="Turning curiosity into inquiry."/><p>Academic work, research exercises,<br/>and directions for future exploration.</p></div><div className="sample-notice"><PenLine size={16}/><p>Sample project topics are shown below. These are illustrative directions, not completed research or verified achievements.</p></div><div className="project-grid">{projects.map((project,i)=><article className={"project-card project-card-"+i} key={project.slug}><div className="project-top"><span className="project-number">0{i+1}</span><span>{project.category}</span></div><div className="project-body"><span className="sample-label">{project.sample?"ILLUSTRATIVE TOPIC":project.year}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-methods">{project.methods.map(m=><span key={m}>{m}</span>)}</div>{project.pdf&&<a href={project.pdf}>Read paper <ArrowUpRight size={16}/></a>}{project.url&&<a href={project.url} target="_blank" rel="noreferrer">View project <ArrowUpRight size={16}/></a>}{project.detailsUrl&&<a href={project.detailsUrl}>Project details</a>}</div></article>)}</div></div></section>
<section className="section-wrap section-pad"><div className="highlights-section reveal"><Heading label="ACADEMIC HIGHLIGHTS" title="A foundation to build on."/><div className="highlights-grid">{highlights.map((h,i)=><article key={h.title}><span>0{i+1}</span><h3>{h.title}</h3><p>{h.description}</p></article>)}</div></div><div className="skills-layout reveal"><Heading label="05 / SKILLS & STRENGTHS" title="Always learning. Always growing." description="Developing the tools to ask better questions and communicate ideas with care."/><div className="skill-groups">{[...skills,...(digitalSkills.published?[{title:"Digital",items:digitalSkills.items}]:[])].map((s,i)=><div className="skill-group" key={s.title}><h3><span>0{i+1}</span>{s.title}</h3><div className="tags">{s.items.map(t=><span key={t}>{t}</span>)}</div></div>)}</div></div>
{publishedExperience.length>0&&<section className="optional-section"><Heading label="BEYOND THE CLASSROOM" title="Experience & Engagement"/><div className="experience-timeline">{publishedExperience.map(e=><article key={e.title}><span>{e.year}</span><h3>{e.title}</h3><p>{e.organization} · {e.location}</p><p>{e.description}</p></article>)}</div></section>}
{publishedCertificates.length>0&&<section className="optional-section"><Heading label="ACADEMIC JOURNEY" title="Certificates & Achievements"/><div className="research-grid">{publishedCertificates.map(c=><article key={c.title} className="research-card"><h3>{c.title}</h3><p>{c.issuer} · {c.date}</p><p>{c.description}</p>{c.image&&<img src={c.image} alt={c.title}/>} {(c.pdf||c.url)&&<a href={c.pdf||c.url}>View certificate</a>}</article>)}</div></section>}
</section><section className="philosophy reveal"><div className="section-wrap"><Quote size={37} strokeWidth={1}/><p className="eyebrow">A THOUGHT I CARRY WITH ME</p><blockquote>“{profile.quote}”</blockquote><p className="quote-attribution">{profile.name}<span>Sociology Undergraduate · University of Dhaka</span></p></div></section>
<section id="contact" className="section-wrap section-pad contact-layout reveal"><div><Heading label="06 / LET’S CONNECT" title="Good conversations can begin something meaningful."/><p className="contact-intro">Open to academic opportunities, research collaborations, internships, volunteering, and meaningful conversations.</p><a className="contact-email" href={"mailto:"+profile.email}><Mail size={21}/><span><small>WRITE TO ME</small>{profile.email}</span><ArrowUpRight size={19}/></a><div className="contact-locations"><div><MapPin size={18}/><span><small>CURRENTLY IN</small>{profile.location}</span></div><div><MapPin size={18}/><span><small>ROOTED IN</small>{profile.hometown}</span></div></div><p className="contact-end">I’m always interested in learning, collaborating, and connecting with people working in research, education, development, and social impact.</p></div><ContactForm/></section>
</main><footer className="footer"><div className="section-wrap"><div className="footer-top"><a href="#home" className="brand"><img src="/favicon.svg" width="40" height="40" alt=""/><span>Kaniz.</span></a><p>Sociology student. Curious mind. Lifelong learner.</p><a href={"mailto:"+profile.email} aria-label="Email Kaniz"><Mail size={21}/></a>{socials.filter(s=>s.url).map(s=><a key={s.label} href={s.url}>{s.label}</a>)}</div><div className="footer-bottom"><Copyright/><nav aria-label="Footer navigation">{navigation.map(n=><a key={n.id} href={"#"+n.id}>{n.label}</a>)}</nav></div></div></footer><Motion/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"Person",name:profile.fullName,alternateName:profile.name,email:profile.email,affiliation:{"@type":"CollegeOrUniversity",name:profile.university},description:profile.description,homeLocation:{"@type":"Place",name:profile.location},knowsAbout:research.map(r=>r.title)})}}/></>}
